version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:
  mobile_build:

networks:
  app-network:
    driver: bridge
