name: "Back: Run Unit Tests"

on:
  push:
    paths:
      - 'back/**'
  pull_request:
    paths:
      - 'back/**'
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        working-directory: back
        run: npm install

      - name: Generate Prisma Client
        working-directory: back
        run: npx prisma generate --schema prismaDb

      - name: Run Tests
        working-directory: back
        run: npm test
