name: "Front: Build Validation"

on:
  push:
    paths:
      - "front/**"
  pull_request:
    paths:
      - "front/**"
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: node:20
      options: -v ${{ github.workspace }}/front
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies and build the application
        working-directory: front
        run: |
          npm install
          npm run build
