name: "Front: Prettier and Format Validation"

on:
  push:
    paths:
      - 'front/**'
  pull_request:
    paths:
      - 'front/**'
    branches: ["main"]

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js using Docker image
        run: |
          docker run --rm -v ${{ github.workspace }}/front:/app -w /app node:20-alpine sh -c "
            npm install &&
            npm run format
          "
