name: "Front: Build Validation"

on:
  push:
    paths:
      - 'front/**'
  pull_request:
    paths:
      - 'front/**'
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the application in Node.js container
        uses: addnab/docker-run-action@v3
        with:
          image: node:20
          options: -v ${{ github.workspace }}/front:/app
          run: |
            cd /app
            npm install
            npm run build
