name: Push mirror

on:
  push:
    branches:
      - main

jobs:
  push_to_mirror:
    name: Push to Epitech repo
    runs-on: ubuntu-24.04
    env:
      MIRROR_URL: "git@github.com:EpitechPromo2027/B-DEV-500-PAR-5-2-area-thibaud.cathala.git"
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror the repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
