name: Push miror

on:
  workflow_call:
    secrets:
      SSH_KEY:
        required: true

jobs:
  push_to_miror:
    name: Push to Epitech repo
    runs-on: ubuntu-24.04
    env:
      MIROR_URL: "git@github.com:EpitechPromo2027/B-DEV-500-PAR-5-2-area-thibaud.cathala.git"
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror the repo
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIROR_URL }}
          ssh_private_key: ${{ secrets.SSH_KEY }}
