name: "Mobile: Lint and Format"

on:
  push:
    paths:
      - 'mobile/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: mobile

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'
          channel: 'stable'
          cache: true

      - name: install dependencies
        run: flutter pub get

      - name: formating check
        run: dart format --set-exit-if-changed .

      # - name: lint check
      #   run: flutter analyze
