name: Conventional PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-for-cc:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v1.0.0
        with:
          pr-title-regex: '^(feat|fix|doc|style|refactor|test|chore)(\([a-zA-Z0-9_-]+\))?: .{1,72}$'
          pr-body-regex: ".*"
